POST https://{{fqdn}}/v1/register/team/
Content-Type: application/json

{
  "team-id": {{team-id-0}}
}

###
POST https://{{fqdn}}/v1/register/team/
Content-Type: application/json

{
  "team-id": {{team-id-1}}
}

###
POST https://{{fqdn}}/v1/register/team/
Content-Type: application/json

{
  "team-id": {{team-id-2}}
}

###
POST https://{{fqdn}}/v1/register/participant/
Content-Type: application/json

{
"participant-id": {{participant-id-0}}
}

###
POST https://{{fqdn}}/v1/register/participant/
Content-Type: application/json

{
"participant-id": {{participant-id-1}}
}

###
POST https://{{fqdn}}/v1/register/participant/
Content-Type: application/json

{
"participant-id": {{participant-id-2}}
}

###
